// Tenant-scope classification of every API route under app/api.
//
// Every route.ts must have exactly one entry here, and __tests__/lib/route-scope-manifest.test.ts
// fails when a route is added without one, when an entry points at a route that no longer exists,
// or when the evidence recorded for an entry is no longer present in the route's source. That makes
// "which tenant check protects this route" a reviewed, drift-proof statement instead of a convention.
//
// Scopes:
//   public               no session. Authorised by a credential or token the caller holds, or open by design.
//   webhook              provider-authenticated. Tenant is derived from stored records, never the payload.
//   cron                 housekeeping trigger.
//   self                 acts only on the session user's own records. The user id comes from the session,
//                        never from the request. Test: the source must not read a client-supplied user id.
//   self-tenant-checked  acts as the session user but references a tenant-owned resource (a class, a
//                        community post, a package). `evidence` names the check that proves the tenant.
//   tenant-staff         staff capability, plus a tenant check on every target. `evidence` names it.
//   own-tenant           staff action on the acting staff member's own gym only, no client target.
//   platform             exact-role platform_operator (lib/permissions.ts PLATFORM_ONLY_CAPABILITIES).
//   global-shared        staff capability over data that is one platform-wide copy by design. Whether this
//                        should become per-gym is an open owner decision (audit 12.2, 12.6).
//
// `evidence` strings are literal source tokens. If a refactor moves a check, update the entry in the
// same change so a reviewer sees the move.

export type RouteScope =
  | "public"
  | "webhook"
  | "cron"
  | "self"
  | "self-tenant-checked"
  | "tenant-staff"
  | "own-tenant"
  | "platform"
  | "global-shared";

export interface RouteScopeEntry {
  /** Path under app/api without the trailing /route.ts, with [param] segments verbatim. */
  route: string;
  scope: RouteScope;
  /** Capability strings the route is gated by. Each must appear literally in the source. */
  capabilities?: string[];
  /** Source tokens proving the tenant check. Each must appear literally in the source. */
  evidence?: string[];
  note?: string;
}

export const ROUTE_SCOPE_MANIFEST: readonly RouteScopeEntry[] = [
  { route: "admin/membership/activate", scope: "tenant-staff", capabilities: ["members.billing"], evidence: ["sameGym(", "staffAuthorizedForCatalogPackage", "ownerGymFor"] },
  { route: "ai/chat", scope: "self" },
  { route: "ai/coach-summary", scope: "tenant-staff", capabilities: ["members.coaching"], evidence: ["sameGym("] },
  { route: "ai/draft-reply", scope: "tenant-staff", capabilities: ["members.coaching"], evidence: ["sameGym("] },
  { route: "ai/nutrition-coach", scope: "self" },
  { route: "auth/check-email", scope: "public", note: "Pre-auth email existence probe; rate limited per email." },
  { route: "auth/forgot-password", scope: "public", note: "Pre-auth; rate limited; responds identically whether or not the account exists." },
  { route: "auth/login", scope: "public", note: "Credential login; the session's tenant comes from the stored account, never the request." },
  { route: "auth/logout", scope: "public", note: "Clears the caller's own cookie." },
  { route: "auth/reset-password", scope: "public", note: "Possession of a single-use reset token authorises the change." },
  { route: "auth/signup", scope: "public", note: "Gym is resolved from a server-verified invite, never from the request body; otherwise the primary gym." },
  { route: "auth/web-handoff", scope: "public", note: "Single-use mobile handoff token mints a session for the token's own user." },
  { route: "billing/webhook", scope: "webhook", note: "Revolut: signature verified; tenant derived from the stored subscription's user, never from the payload." },
  { route: "bookings/cancel", scope: "self-tenant-checked", evidence: ["sameGym("] },
  { route: "bookings/create", scope: "self-tenant-checked", evidence: ["sameGymAsStaff"] },
  { route: "bookings/waitlist/join", scope: "self-tenant-checked", evidence: ["sameGymAsStaff"] },
  { route: "bookings/waitlist/leave", scope: "self" },
  { route: "bookings/waitlist/respond", scope: "self-tenant-checked", evidence: ["sameGymAsStaff", "sameGym("] },
  { route: "bug-reports/create", scope: "self" },
  { route: "contact", scope: "public", note: "Anonymous contact form into the platform inbox." },
  { route: "cron/run", scope: "cron", capabilities: ["platform.jobs"], note: "Session path needs platform.jobs (exact platform_operator role); the other path is a constant-time CRON_SECRET." },
  { route: "cycle/preferences", scope: "self" },
  { route: "cycle/privacy", scope: "self" },
  { route: "cycle/settings", scope: "self" },
  { route: "exercise-library", scope: "self" },
  { route: "exercise-library/[slug]", scope: "self" },
  { route: "exercise-library/favorites", scope: "self" },
  { route: "exercise-library/names", scope: "self" },
  { route: "gyms/signup", scope: "public", note: "Anonymous self-serve tenant creation; the new gym starts unapproved and only a platform operator can approve it." },
  { route: "invites/redeem", scope: "self-tenant-checked", evidence: ["sameGymAsStaff", "resolveInviteGymId"] },
  { route: "membership/checkout", scope: "self-tenant-checked", evidence: ["sameGym(", "isGlobalCatalogPackage", "catalogScopesMatch", "ownerGymFor"] },
  { route: "messages/send", scope: "self-tenant-checked", evidence: ["sameGym("] },
  { route: "mobile/auth/login", scope: "public", note: "Credential login; the session's tenant comes from the stored account." },
  { route: "mobile/auth/me", scope: "self" },
  { route: "mobile/auth/signup", scope: "public", note: "Gym is resolved from a server-verified invite, never from the request body; otherwise the primary gym." },
  { route: "mobile/auth/web-handoff", scope: "self" },
  { route: "mobile/billing/google-play/verify", scope: "self" },
  { route: "mobile/coach/provision-member-profile", scope: "self" },
  { route: "mobile/community/comments/[id]", scope: "self" },
  { route: "mobile/community/comments/[id]/report", scope: "self-tenant-checked", evidence: ["sameGymAsStaff"] },
  { route: "mobile/community/feed", scope: "self-tenant-checked", evidence: ["sameGymAsStaff"] },
  { route: "mobile/community/follow", scope: "self-tenant-checked", evidence: ["sameGymAsStaff"] },
  { route: "mobile/community/highlight", scope: "self-tenant-checked", evidence: ["sameGymAsStaff", "sameGym("] },
  { route: "mobile/community/leaderboard", scope: "self-tenant-checked", evidence: ["sameGym("] },
  { route: "mobile/community/privacy", scope: "self" },
  { route: "mobile/community/search", scope: "self-tenant-checked", evidence: ["sameGym(", "getStaffMembersData"] },
  { route: "mobile/community/unfollow", scope: "self-tenant-checked", evidence: ["sameGymAsStaff"] },
  { route: "mobile/community/wins", scope: "self-tenant-checked", evidence: ["sameGymAsStaff"] },
  { route: "mobile/community/workouts/[id]", scope: "self-tenant-checked", evidence: ["sameGymAsStaff"] },
  { route: "mobile/community/workouts/[id]/comments", scope: "self-tenant-checked", evidence: ["sameGymAsStaff"] },
  { route: "mobile/community/workouts/[id]/like", scope: "self-tenant-checked", evidence: ["sameGymAsStaff"] },
  { route: "mobile/cycle", scope: "self" },
  { route: "mobile/dashboard", scope: "self" },
  { route: "mobile/equipment-catalog", scope: "self" },
  { route: "mobile/gym-profiles", scope: "self" },
  { route: "mobile/gym-profiles/delete", scope: "self" },
  { route: "mobile/gym-profiles/set-active", scope: "self" },
  { route: "mobile/gym-profiles/update", scope: "self" },
  { route: "mobile/gyms/geocode", scope: "self" },
  { route: "mobile/gyms/my-gym/visibility", scope: "own-tenant", capabilities: ["gym.manageAvailability"], evidence: ["gymId"], note: "Acts only on the acting staff member's own gym, resolved from their account." },
  { route: "mobile/gyms/nearby", scope: "self" },
  { route: "mobile/hydration", scope: "self" },
  { route: "mobile/membership", scope: "self" },
  { route: "mobile/messages", scope: "self" },
  { route: "mobile/notifications", scope: "self" },
  { route: "mobile/notifications/[id]/read", scope: "self" },
  { route: "mobile/notifications/read-all", scope: "self" },
  { route: "mobile/nutrition", scope: "self" },
  { route: "mobile/nutrition/diary", scope: "self" },
  { route: "mobile/nutrition/diary/create", scope: "self" },
  { route: "mobile/nutrition/diary/delete", scope: "self" },
  { route: "mobile/nutrition/diary/recent", scope: "self" },
  { route: "mobile/nutrition/food/barcode", scope: "self" },
  { route: "mobile/nutrition/food/custom", scope: "self" },
  { route: "mobile/nutrition/food/custom/create", scope: "self" },
  { route: "mobile/nutrition/food/custom/delete", scope: "self" },
  { route: "mobile/nutrition/food/custom/update", scope: "self" },
  { route: "mobile/nutrition/food/describe", scope: "self" },
  { route: "mobile/nutrition/food/favorites", scope: "self" },
  { route: "mobile/nutrition/food/favorites/add", scope: "self" },
  { route: "mobile/nutrition/food/favorites/delete", scope: "self" },
  { route: "mobile/nutrition/food/identification-override", scope: "self" },
  { route: "mobile/nutrition/food/label-scan", scope: "self" },
  { route: "mobile/nutrition/food/report-missing", scope: "self" },
  { route: "mobile/nutrition/food/search", scope: "self" },
  { route: "mobile/nutrition/food/submission/create", scope: "self" },
  { route: "mobile/nutrition/food/submission/mine", scope: "self" },
  { route: "mobile/nutrition/meal-suggest", scope: "self" },
  { route: "mobile/nutrition/receipt-scan", scope: "self" },
  { route: "mobile/nutrition/recipes", scope: "self" },
  { route: "mobile/nutrition/recipes/create", scope: "self" },
  { route: "mobile/nutrition/recipes/delete", scope: "self" },
  { route: "mobile/nutrition/shopping-list", scope: "self" },
  { route: "mobile/nutrition/shopping-list/add", scope: "self" },
  { route: "mobile/nutrition/shopping-list/delete", scope: "self" },
  { route: "mobile/nutrition/shopping-list/toggle", scope: "self" },
  { route: "mobile/nutrition/target", scope: "self" },
  { route: "mobile/nutrition/target/member-override", scope: "self" },
  { route: "mobile/nutrition/targets/week", scope: "self" },
  { route: "mobile/pregnancy", scope: "self" },
  { route: "mobile/profile", scope: "self" },
  { route: "mobile/programs", scope: "self" },
  { route: "mobile/programs/[id]/apply-adjustment", scope: "self" },
  { route: "mobile/programs/[id]/checkin/[cycle]", scope: "self" },
  { route: "mobile/programs/[id]/exercises/[exerciseId]/alternatives", scope: "self" },
  { route: "mobile/programs/[id]/exercises/[exerciseId]/swap", scope: "self" },
  { route: "mobile/programs/[id]/status", scope: "self" },
  { route: "mobile/programs/advance", scope: "self" },
  { route: "mobile/programs/archive", scope: "self" },
  { route: "mobile/programs/generate", scope: "self" },
  { route: "mobile/programs/save", scope: "self" },
  { route: "mobile/programs/sync-weekly-schedule", scope: "self" },
  { route: "mobile/push", scope: "self" },
  { route: "mobile/recovery", scope: "self" },
  { route: "mobile/schedule", scope: "self" },
  { route: "mobile/staff/business", scope: "tenant-staff", capabilities: ["finance.view", "reports.view"], evidence: ["getStaffBusinessData"] },
  { route: "mobile/staff/class-categories", scope: "tenant-staff", capabilities: ["classes.manage"], evidence: ["sameGym("] },
  { route: "mobile/staff/classes", scope: "tenant-staff", capabilities: ["classes.manage"], evidence: ["getStaffClassesData"] },
  { route: "mobile/staff/classes/[classId]/workout", scope: "tenant-staff", capabilities: ["classes.manage"], evidence: ["sameGymAsStaff", "sameGym("] },
  { route: "mobile/staff/members", scope: "tenant-staff", capabilities: ["members.view"], evidence: ["sameGym(", "getStaffMembersData"] },
  { route: "mobile/staff/members/[userId]", scope: "tenant-staff", capabilities: ["members.view"], evidence: ["sameGym(", "getStaffMemberDetail"] },
  { route: "mobile/staff/messages", scope: "tenant-staff", capabilities: ["members.view"], evidence: ["sameGym("] },
  { route: "mobile/staff/messages/[memberId]", scope: "tenant-staff", capabilities: ["members.view"], evidence: ["sameGym("] },
  { route: "mobile/staff/nutrition-target", scope: "tenant-staff", capabilities: ["nutrition.manage"], evidence: ["sameGym("] },
  { route: "mobile/staff/nutrition-target/update", scope: "tenant-staff", capabilities: ["nutrition.manage"], evidence: ["sameGym("] },
  { route: "mobile/staff/nutrition/moderation", scope: "global-shared", capabilities: ["foodCatalog.manage"], note: "Shared food catalogue moderation queue." },
  { route: "mobile/staff/nutrition/moderation/resolve", scope: "global-shared", capabilities: ["foodCatalog.manage"], note: "Shared food catalogue moderation." },
  { route: "mobile/staff/nutrition/submissions", scope: "global-shared", capabilities: ["foodCatalog.manage"], note: "Shared food catalogue submissions." },
  { route: "mobile/staff/nutrition/submissions/review", scope: "global-shared", capabilities: ["foodCatalog.manage"], note: "Shared food catalogue submissions." },
  { route: "mobile/staff/programs", scope: "tenant-staff", capabilities: ["programs.manage"], evidence: ["sameGym(", "getStaffTrainingPrograms"] },
  { route: "mobile/staff/programs/create", scope: "tenant-staff", capabilities: ["programs.manage"], evidence: ["sameGym("] },
  { route: "mobile/staff/programs/delete", scope: "tenant-staff", capabilities: ["programs.manage"], evidence: ["sameGym("] },
  { route: "mobile/staff/programs/update", scope: "tenant-staff", capabilities: ["programs.manage"], evidence: ["sameGym("] },
  { route: "mobile/staff/workout-templates", scope: "tenant-staff", capabilities: ["classes.manage"], evidence: ["findClassWorkoutTemplatesForStaff"] },
  { route: "mobile/tracker-import/scan", scope: "self" },
  { route: "mobile/weekly-training", scope: "self" },
  { route: "mobile/workout-helper/tier", scope: "self" },
  { route: "mobile/workout-review/[id]", scope: "self" },
  { route: "mobile/workout-templates", scope: "self" },
  { route: "mobile/workout-templates/create", scope: "self" },
  { route: "mobile/workout-templates/delete", scope: "self" },
  { route: "mobile/workout-templates/update", scope: "self" },
  { route: "mobile/workouts", scope: "self" },
  { route: "mobile/workouts/[id]/visibility", scope: "self" },
  { route: "notifications", scope: "self" },
  { route: "notifications/[id]/read", scope: "self" },
  { route: "notifications/read-all", scope: "self" },
  { route: "nutrition/target", scope: "self" },
  { route: "pregnancy/status", scope: "self" },
  { route: "profile/appearance", scope: "self" },
  { route: "profile/body-fat", scope: "self" },
  { route: "profile/body-weight", scope: "self" },
  { route: "profile/change-email/confirm", scope: "public", note: "Possession of a single-use confirmation token authorises the change." },
  { route: "profile/change-email/request", scope: "self" },
  { route: "profile/drink-settings", scope: "self" },
  { route: "profile/email-notifications", scope: "self" },
  { route: "profile/goal", scope: "self" },
  { route: "profile/goal-timeline", scope: "self" },
  { route: "profile/pinned-exercises", scope: "self" },
  { route: "profile/pinned-progression-exercises", scope: "self" },
  { route: "profile/push-notifications", scope: "self" },
  { route: "profile/reminders", scope: "self" },
  { route: "profile/rest-timer", scope: "self" },
  { route: "profile/tour", scope: "self" },
  { route: "profile/units", scope: "self" },
  { route: "profile/update", scope: "self" },
  { route: "programme/update", scope: "self" },
  { route: "push/subscribe", scope: "self" },
  { route: "recovery/log", scope: "self-tenant-checked", evidence: ["sameGym("] },
  { route: "staff/attendance/watchlist/delete", scope: "tenant-staff", capabilities: ["classes.manage"], evidence: ["sameGymAsStaff"] },
  { route: "staff/bookings/attendance", scope: "tenant-staff", capabilities: ["classes.manage"], evidence: ["sameGymAsStaff"] },
  { route: "staff/bookings/remove", scope: "tenant-staff", capabilities: ["classes.manage"], evidence: ["sameGymAsStaff"] },
  { route: "staff/bug-reports/delete", scope: "tenant-staff", capabilities: ["bugReports.manage"], evidence: ["sameGym("] },
  { route: "staff/bug-reports/status", scope: "tenant-staff", capabilities: ["bugReports.manage"], evidence: ["sameGym("] },
  { route: "staff/catalog/billing-options", scope: "tenant-staff", capabilities: ["catalog.manage"], evidence: ["staffAuthorizedForCatalogPackage"] },
  { route: "staff/catalog/billing-options/delete", scope: "tenant-staff", capabilities: ["catalog.manage"], evidence: ["staffAuthorizedForCatalogPackage"] },
  { route: "staff/catalog/categories", scope: "tenant-staff", capabilities: ["catalog.manage"], evidence: ["sameGym("] },
  { route: "staff/catalog/categories/delete", scope: "tenant-staff", capabilities: ["catalog.manage"], evidence: ["sameGym("] },
  { route: "staff/catalog/packages", scope: "tenant-staff", capabilities: ["catalog.manage"], evidence: ["staffAuthorizedForCatalogPackage", "isGlobalCatalogPackage", "isPlatformOperator"] },
  { route: "staff/catalog/packages/delete", scope: "tenant-staff", capabilities: ["catalog.manage"], evidence: ["staffAuthorizedForCatalogPackage"] },
  { route: "staff/categories", scope: "tenant-staff", capabilities: ["operations.view"], evidence: ["sameGym("] },
  { route: "staff/categories/delete", scope: "tenant-staff", capabilities: ["operations.view"], evidence: ["sameGym("] },
  { route: "staff/classes", scope: "tenant-staff", capabilities: ["classes.manage"], evidence: ["sameGymAsStaff", "sameGym("] },
  { route: "staff/classes/[classId]/workout", scope: "tenant-staff", capabilities: ["classes.manage"], evidence: ["sameGymAsStaff"] },
  { route: "staff/classes/delete", scope: "tenant-staff", capabilities: ["classes.manage"], evidence: ["sameGymAsStaff"] },
  { route: "staff/classes/series/stop", scope: "tenant-staff", capabilities: ["classes.manage"], evidence: ["sameGymAsStaff"] },
  { route: "staff/community/reports/[id]/resolve", scope: "tenant-staff", capabilities: ["comments.moderate"], evidence: ["sameGym("] },
  { route: "staff/exercise-library", scope: "global-shared", capabilities: ["exercises.manage"], note: "Shared exercise library; any gym's staff can mutate it (owner decision: audit 12.2)." },
  { route: "staff/exercise-library/[id]", scope: "global-shared", capabilities: ["exercises.manage"], note: "Shared exercise library." },
  { route: "staff/exercise-library/[id]/approve", scope: "global-shared", capabilities: ["exercises.manage"], note: "Shared exercise library." },
  { route: "staff/exercise-library/import", scope: "global-shared", capabilities: ["exercises.manage"], note: "Shared exercise library." },
  { route: "staff/exercise-library/logs", scope: "global-shared", capabilities: ["exercises.manage"], note: "Shared exercise library." },
  { route: "staff/exercises", scope: "global-shared", capabilities: ["exercises.manage"], note: "Shared exercise catalogue." },
  { route: "staff/exercises/bulk-delete", scope: "global-shared", capabilities: ["exercises.manage"], note: "Shared exercise catalogue." },
  { route: "staff/exercises/delete", scope: "global-shared", capabilities: ["exercises.manage"], note: "Shared exercise catalogue." },
  { route: "staff/exercises/generate", scope: "global-shared", capabilities: ["exercises.manage"], note: "Shared exercise catalogue." },
  { route: "staff/exercises/import-starter", scope: "global-shared", capabilities: ["exercises.manage"], note: "Shared exercise catalogue." },
  { route: "staff/finance/ledger", scope: "platform", capabilities: ["finance.view"] },
  { route: "staff/finance/ledger/delete", scope: "platform", capabilities: ["finance.view"] },
  { route: "staff/gyms/[gymId]/status", scope: "platform", capabilities: ["gyms.moderate"] },
  { route: "staff/invites", scope: "tenant-staff", capabilities: ["members.billing"], evidence: ["sameGymAsStaff"] },
  { route: "staff/invites/[inviteId]/revoke", scope: "tenant-staff", capabilities: ["members.billing"], evidence: ["sameGymAsStaff"] },
  { route: "staff/members/[userId]/ai-usage", scope: "tenant-staff", capabilities: ["members.view"], evidence: ["sameGym("] },
  { route: "staff/members/[userId]/archive", scope: "tenant-staff", capabilities: ["members.account"], evidence: ["sameGym("] },
  { route: "staff/members/[userId]/delete", scope: "tenant-staff", capabilities: ["members.hardDelete"], evidence: ["sameGym("] },
  { route: "staff/members/[userId]/extra-sessions", scope: "tenant-staff", capabilities: ["members.billing"], evidence: ["sameGym("] },
  { route: "staff/members/[userId]/pause", scope: "tenant-staff", capabilities: ["members.billing"], evidence: ["sameGym("] },
  { route: "staff/members/[userId]/subscription", scope: "tenant-staff", capabilities: ["members.billing"], evidence: ["sameGym(", "staffAuthorizedForCatalogPackage", "ownerGymFor"] },
  { route: "staff/members/[userId]/tier", scope: "tenant-staff", capabilities: ["members.grantTier"], evidence: ["sameGym("] },
  { route: "staff/members/bulk-tier", scope: "tenant-staff", capabilities: ["members.grantTier"], evidence: ["sameGymAsStaff"] },
  { route: "staff/members/notes", scope: "tenant-staff", capabilities: ["members.edit"], evidence: ["sameGym("] },
  { route: "staff/members/reset-password", scope: "tenant-staff", capabilities: ["members.account"], evidence: ["sameGym(", "targetOutranksActor", "protectedOperatorTarget"] },
  { route: "staff/members/update", scope: "tenant-staff", capabilities: ["members.edit", "members.account"], evidence: ["sameGym(", "targetOutranksActor", "protectedOperatorTarget"] },
  { route: "staff/messages/unread-count", scope: "tenant-staff", capabilities: ["members.view"], evidence: ["sameGym("] },
  { route: "staff/settings/emails", scope: "global-shared", capabilities: ["operations.view"], note: "Singleton platform email toggles." },
  { route: "staff/settings/finance", scope: "platform", capabilities: ["finance.view"] },
  { route: "staff/settings/readiness-alert", scope: "global-shared", capabilities: ["operations.view"], note: "Singleton readiness-alert settings." },
  { route: "staff/staff-users", scope: "tenant-staff", capabilities: ["staffUsers.manage"], evidence: ["sameGym(", "protectedOperatorTarget"] },
  { route: "staff/staff-users/archive", scope: "tenant-staff", capabilities: ["staffUsers.manage"], evidence: ["sameGym(", "protectedOperatorTarget"] },
  { route: "staff/workout-templates", scope: "tenant-staff", capabilities: ["classes.manage"], evidence: ["templateInStaffGym"] },
  { route: "staff/workout-templates/delete", scope: "tenant-staff", capabilities: ["classes.manage"], evidence: ["templateInStaffGym"] },
  { route: "stripe/webhook", scope: "webhook", note: "Stripe: signature verified; tenant derived from stored records, never from the payload." },
  { route: "webhooks/google-play", scope: "webhook", note: "Google Pub/Sub push: shared-secret token; tenant derived from the stored purchase's user." },
  { route: "workouts/create", scope: "self" },
  { route: "workouts/delete", scope: "self" },
  { route: "workouts/edit", scope: "self" },
  { route: "workouts/update", scope: "self" },
] as const;
